//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canteen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes_Products
    {
        public long Id { get; set; }
        public long DishId { get; set; }
        public long ProductId { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Product Product { get; set; }
    }
}
