//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canteen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_Benefits
    {
        public long Id { get; set; }
        public long StudentId { get; set; }
        public long BenefitId { get; set; }
    
        public virtual Benefit Benefit { get; set; }
        public virtual Student Student { get; set; }
    }
}
